version: '3.7'
services:
    app:
        build:
            context: ./docker/php
            args:
                UID: '${UID}'
                GID: '${GID}'
        image: runitonce:latest
        container_name: runitonce-php
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./src:/app
            - ./docker/php/supervisor.ini:/etc/supervisor.d/runitonce.ini
        # environment:
            # XDEBUG_MODE: debug
        # depends_on: [nginx, 'redis', 'mariadb', 'selenium']
    nginx:
        image: nginx:alpine
        container_name: runitonce-www
        restart: unless-stopped
        working_dir: /etc/nginx
        volumes:
            - ./src:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '${HTTP_PORT:-8080}:80'
        healthcheck:
            test: ['CMD', 'nginx', 'ping']
    mariadb:
        image: 'mariadb:latest'
        container_name: runitonce-db
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-docker}'
            MYSQL_DATABASE: '${DB_DATABASE:-runitonce}'
            MYSQL_USER: '${DB_USERNAME:-docker}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-docker}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'runitonce-db:/var/lib/mysql'
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        #     retries: 3
        #     timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: runitonce-redis
        restart: unless-stopped
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'runitonce-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: runitonce-mail
        restart: unless-stopped
        ports:
            - '${MAILHOG_SMTP_PORT:-1025}:1025'
            - '${MAILHOG_HTTP_PORT:-8025}:8025'
    selenium:
        image: 'selenium/standalone-chrome-debug'
        container_name: runitonce-selenium
        restart: unless-stopped
        environment:
            - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
        volumes:
            - '/dev/shm:/dev/shm'

volumes:
    runitonce-db:
        name: runitonce-db
        driver: local
    runitonce-redis:
        name: runitonce-redis
        driver: local